create table if not exists conversations (
    id bigint generated by default as identity primary key,
    user_id text not null default 'default',
    role text not null check (role in ('user', 'assistant')),
    content text not null,
    created_at timestamptz not null default now()
);

create index if not exists idx_conversations_user_created
    on conversations (user_id, created_at desc);
